use packer for base image
Neokarm/neokarm-examples pull request #12
Opened 2022-03-21 15:01 UTC by Slevy35

2022-04-04 17:31 UTC, roeigo-stratoscale submitted a review, later dismissed

2022-04-17 09:33 UTC, IliaFeldgun requested changes

2022-04-17 17:01 UTC, Slevy35 commented on k8s/install/terraform/variables.tf
> +variable "install_custome_ca_certificate" {
my bad, will fix

2022-04-17 17:03 UTC, Slevy35 commented on k8s/install/packer/files/cgroup-memory-fix.sh
> +#sudo sed -i "/.*cgroup.memory=nokmem.*/$(echo -e "\0041")s/^GRUB_CMDLINE_LINUX=\".*$/$(cat /etc/default/grub | grep  '^GRUB_CMDLINE_LINUX=\".*$' | sed -e 's/[ \t]*$//' | sed  "s/\"$/ cgroup.memory=n
https://zadara.atlassian.net/browse/ZSTRG-18100

2022-04-19 08:36 UTC, IliaFeldgun approved these changes

2022-04-19 08:50 UTC, merged