Calico Networking K8s
Neokarm/neokarm-examples pull request #9
Opened 2022-02-11 13:04 UTC by YotamNordman

2022-02-13 14:30 UTC, Slevy35 requested changes

2022-02-13 14:30 UTC, Slevy35 commented on k8s/calico-networking/README.md
> +- Install calicoctl in order to interact with calico
add link to documentation

2022-02-13 14:30 UTC, Slevy35 commented on k8s/calico-networking/README.md
> +Again, Monitor the calico-node daemonset that should restart.
```suggestion
> Important: Verify that all of the calico-node pods are restarting.
```

2022-02-13 14:30 UTC, Slevy35 commented on k8s/install/terraform/rke.tf
> +    host        = aws_eip.bastion_eip.public_ip
use the bastion as jump server

2022-02-13 14:30 UTC, Slevy35 commented on k8s/install/terraform/rke.tf
> +  count  = "${var.bgp == "true" ? 1 : 0}"
fix bool

2022-02-14 16:57 UTC, Slevy35 requested changes

2022-02-15 09:04 UTC, YotamNordman commented on k8s/calico-networking/bgpconfiguration.yaml
> +  listenPort: 178
you're right, but it worked for us with 178 ill change it anyway

2022-02-15 10:46 UTC, Slevy35 requested changes

2022-02-15 10:46 UTC, Slevy35 commented on k8s/install/terraform/rke.tf
> +  count  = "${var.bgp == true ? var.rke_servers_count - 1 : 0}"
where is the seeder?

2022-02-15 10:46 UTC, Slevy35 commented on k8s/install/terraform/variables.tf
> +variable "bgp" {
change to `bgp_enabled`

2022-02-15 12:56 UTC, Slevy35 approved these changes

2022-02-16 06:46 UTC, merged